# font
font_family      CaskaydiaCove Nerd Font Mono
font_size	 9.0
bold_font        auto
italic_font      auto
bold_italic_font auto

# performance
enable_audio_bell no
repaint_delay    10
input_delay      3
sync_to_monitor  yes

# GPU rendering
background_opacity 0.60

# Scrollback
scrollback_lines 5000

# Cursor
cursor_shape block
cursor_blink_interval 0

# Colors (dark clean)
#foreground #cdd6f4
#background #1e1e2e

# Window
window_padding_width 24
confirm_os_window_close 0

include theme.conf

#cursor_trail 1
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0

# initially empty, to be configured by user and remains static
include userprefs.conf

# Note: as userprefs.conf is included at the end, settings configured in this file will override the defaults
