# ===== Hyprland =====
env = HYPRLAND_NO_RT,1
env = HYPRLAND_NO_SD_NOTIFY,1
env = HYPRLAND_NO_SD_VARS,1

# ===== Mesa =====
env = MESA_SHADER_CACHE_DISABLE,false
env = MESA_SHADER_CACHE_MAX_SIZE,2G

# ===== OpenGL =====
env = mesa_glthread,true

# ===== Wine (nhẹ, an toàn) =====
env = WINEESYNC,1
env = WINEDEBUG,-all

