# ===== Hyprland =====
env = HYPRLAND_NO_RT,1

# ===== wlroots =====
# Bật atomic nếu không bị flicker
# env = WLR_DRM_NO_ATOMIC,1

# ===== RADV tuning =====
env = RADV_PERFTEST,gpl,nggc

# ===== Mesa =====
env = MESA_SHADER_CACHE_DISABLE,false
env = MESA_SHADER_CACHE_MAX_SIZE,4G
env = __GL_SHADER_DISK_CACHE,1
env = __GL_SHADER_DISK_CACHE_PATH,/home/ten_user/.cache/mesa_shader_cache
env = mesa_glthread,true

# ===== DXVK =====
env = DXVK_ASYNC,1
env = DXVK_LOG_LEVEL,none

# ===== Wine =====
env = WINEESYNC,1
env = WINEFSYNC,1
env = WINE_VK_USE_WSI,x11
env = WINEDEBUG,-all

