source = ./hyprland/keybindings.conf
source = ./hyprland/monitors.conf
source = ./hyprland/env.conf

exec-once = waybar
exec-once = hypridle
exec-once = hyprpaper
exec-once = fcitx5

general {
	border_size = 1
    	gaps_in = 1
    	gaps_out = 1
    	col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    	col.inactive_border = rgba(595959aa)
    	layout = dwindle
	allow_tearing = true
}

decoration {
    	rounding = 2

    	blur {
        	enabled = false
    	}
	shadow {
		enabled = false
	}
}

animations {
	enabled = false
}
 
misc {
	disable_splash_rendering = true
	disable_hyprland_logo = true
    	mouse_move_enables_dpms = false
}

render {
    	direct_scanout = 2
	new_render_scheduling = true
}

cursor {
	no_hardware_cursors = false
    	inactive_timeout = 5.0
	hide_on_key_press = true
}


input {
	kb_layout = us,vn
    	kb_options = grp:alt_shift_toggle
	follow_mouse = 1
	accel_profile = flat
	repeat_delay = 200
	repeat_rate = 50
	sensitivity = 0
}

xwayland {
    	force_zero_scaling = true
	use_nearest_neighbor = false
}
